<div class="tva-flex course-form-header tva-space-between pb-50">
	<div class="title-box mr-20">
		<h1 class="tva-main-heading" id="tva-course-title"><#= model.get('name') #></h1>
		<span class="click" data-fn="editTitle"><?php tva_get_svg_icon( 'pencil-custom' ); ?></span>
		<div style="display: none;">
			<input placeholder="<?php echo esc_html__( 'Course name', 'thrive-apprentice' ); ?>" id="tva-course-<#= model.get('id') #>-name" type="text" data-bind="name">
			<label for="tva-course-<#= model.get('id') #>-name"></label>
		</div>
	</div>
	<div>
		<a id="tva-course-preview" class="tva-btn tva-btn-simple mr-40" target="_blank" style="display: <#-  model.get('preview_url') && model.get('preview_url').length ? 'inline-block' : 'none' #>" href="<#= model.get('preview_url') #>"><?php echo esc_html__( 'Preview course', 'thrive-apprentice' ); ?></a>
		<button id="tva-course-publish" class="tva-btn tva-btn-wide click" data-fn="changeStatus"><?php echo esc_html__( 'Publish', 'thrive-apprentice' ); ?></button>
	</div>
</div>
<div class="tva-flex course-form-dropdowns" id="tva-course-dropdowns"></div>
<div class="tva-course-save">
	<button class="tva-save-btn click" data-fn="saveCourse"><?php echo esc_html__( 'Save', 'thrive-apprentice' ); ?></button>
</div>
