<button class="tva-add-content-btn click" data-fn="openAddItemModal"><?php tva_get_svg_icon( 'plus_light' ); ?></button>
<div class="tva-mass-actions tva-flex tva-align-center pt-20 pl-20">
	<label class="tva-label mr-20" for="tva-check-all">
		<input type="checkbox" class="tva-checkbox" id="tva-check-all">
		<?php esc_html_e( 'Select all', TVA_Const::T ); ?>
	</label>
	<a href="javascript:void(0)" class="click tva-mass-action tva-inline-flex-mid mr-20 publish-group" data-fn="massAction" data-action="publish">
		<?php tva_get_svg_icon( 'publish' ); ?>
		&nbsp;
		<?php esc_html_e( 'Publish', TVA_Const::T ); ?>
	</a>
	<a href="javascript:void(0)" class="click tva-mass-action tva-inline-flex-mid mr-20 unpublish-group" data-fn="massAction" data-action="unpublish">
		<?php tva_get_svg_icon( 'unpublish' ); ?>
		&nbsp;
		<?php esc_html_e( 'Unpublish', TVA_Const::T ); ?>
	</a>
	<a href="javascript:void(0)" class="click tva-mass-action tva-mass-delete tva-inline-flex-mid mr-20" data-fn="massAction" data-action="delete">
		<?php tva_get_svg_icon( 'trash-1' ); ?>
		&nbsp;
		<?php esc_html_e( 'Delete', TVA_Const::T ); ?>
	</a>
	<a href="javascript:void(0)" class="click tva-mass-action tva-inline-flex-mid mr-20 module-group" data-fn="structureAction" data-action="moduleGroup">
		<?php tva_get_svg_icon( 'group' ); ?>
		&nbsp;
		<?php esc_html_e( 'Group into a module', TVA_Const::T ); ?>
	</a>
	<a href="javascript:void(0)" class="click tva-mass-action tva-inline-flex-mid mr-20 chapter-group" data-fn="structureAction" data-action="chapterGroup">
		<?php tva_get_svg_icon( 'group' ); ?>
		&nbsp;
		<?php esc_html_e( 'Group into a chapter', TVA_Const::T ); ?>
	</a>
	<a href="javascript:void(0)" class="click tva-mass-action tva-inline-flex-mid mr-20 mass-move" data-fn="structureAction" data-action="move">
		<?php tva_get_svg_icon( 'move' ); ?>
		&nbsp;
		<?php esc_html_e( 'Move to another course', TVA_Const::T ); ?>
	</a>
</div>
<div class="tva-course-items-wrapper"></div>
<a id="tva-add-item" class="tva-add-main-btn click" data-fn="openAddItemModal" data-type="<#= this.collection.getSingularType() #>" href="javascript:void(0)">
	<?php tva_get_svg_icon( 'plus_light' ); ?>
</a>
