<div class="tva-flex tva-align-center mb-20 tva-space-between">
	<h1 class="tva-main-heading"><?php esc_html_e( 'Dynamic Labels', TVA_Const::T ) ?></h1>
	<a href="javascript:void(0)" class="tva-btn tva-btn-blue click" data-fn="add">
		<?php tva_get_svg_icon( 'add-btn' ); ?>
		<?php esc_html_e( 'Add Label', TVA_Const::T ); ?></a>
</div>

<h5 class="mt-0 tva-label-section-title">
	<?php esc_html_e( 'Access restriction labels', TVA_Const::T ); ?>
	<div class="tva-info-icon tva-relative tva-tooltip-parent tva-mega-tooltip">
		<?php tva_get_svg_icon( 'info-solid' ); ?>
		<div class="tva-custom-tooltip tva-tt-labels">
			<p class="mt-0 mb-10"><strong><?php esc_html_e( 'Labels show the access restrictions on a course', TVA_Const::T ); ?></strong></p>
			<p><?php esc_html_e( 'Labels help the user to understand which courses they:', TVA_Const::T ); ?></p>
			<ul class="m-0">
				<li><?php esc_html_e( 'are unable to access', TVA_Const::T ); ?></li>
				<li><?php esc_html_e( 'have access to but haven’t started', TVA_Const::T ); ?></li>
				<li><?php esc_html_e( 'have already started', TVA_Const::T ); ?></li>
				<li><?php esc_html_e( 'have finished', TVA_Const::T ); ?></li>
			</ul>
			<p class="mt-10"><?php esc_html_e( 'Labels switch depending on the situation.', TVA_Const::T ); ?></p>
			<p class="mt-10"><?php esc_html_e( 'For example, a user that doesn’t have access to a course might see the label “Premium course”, whereas a user that has already purchased the course might see the label “Not started yet”.', TVA_Const::T ); ?></p>
			<p class="mt-10">
				<a href="https://help.thrivethemes.com/en/articles/4698649-how-to-use-the-dynamic-access-restriction-labels-in-thrive-apprentice" target="_blank"><?php esc_html_e( 'Learn more about course labels', TVA_Const::T ); ?></a>
			</p>
		</div>
	</div>
</h5>
<div class="tva-labels-grid mt-5"></div>

<section class="tva-label-switch mt-30 mb-30">
	<label class="tva-slide-checkbox">
		<span class="tva-label-section-title mr-10" style="width:auto"><?php esc_html_e( 'Switch labels depending on user status', TVA_Const::T ); ?></span>
		<input type="checkbox" class="change" data-fn="toggleLabelsSection"<#=this.settings.get('switch_labels') ? ' checked' : ''#>>
		<span class="lever ml-0"></span>
	</label>
	<div class="tva-user-contexts<#=this.settings.get('switch_labels') ? ' tva-expanded' : ''#>"></div>
</section>

<h5 class="mt-0 tva-label-section-title">
	<?php esc_html_e( 'Call to action buttons', TVA_Const::T ); ?>
	<div class="tva-info-icon tva-tooltip-parent tva-mega-tooltip">
		<?php tva_get_svg_icon( 'info-solid' ); ?>
		<div class="tva-custom-tooltip tva-tt-cta">
			<p class="mt-10 mb-10"><strong><?php esc_html_e( 'Buttons help the user navigate around your courses', TVA_Const::T ); ?></strong></p>
			<p class="mb-10"><?php esc_html_e( 'The buttons inside Thrive Apprentice intelligently update so that they reflect the state of the course participant.', TVA_Const::T ); ?></p>
			<p class="mb-10"><?php esc_html_e( 'For example, if a customer doesn’t have access to a course, the button might say “Sign up now“ and, when clicked, will take the user to the purchase page.', TVA_Const::T ); ?></p>
			<p class="mb-10"><?php esc_html_e( 'If the user already has access, the button might say "Start course" and take the user to the first lesson.', TVA_Const::T ); ?></p>
			<p class="m-0">
				<a href="https://help.thrivethemes.com/en/articles/4698654-how-to-use-the-call-to-action-buttons-when-setting-up-thrive-apprentice-dynamic-labels" target="_blank"><?php esc_html_e( 'Learn more about button behavior in Apprentice', TVA_Const::T ); ?></a>
			</p>
		</div>
	</div>
</h5>
<div id="tva-cta-buttons"></div>
