<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<h3 class="tvd-modal-title"><?php echo esc_html__( 'Add Lesson', 'thrive-apprentice' ); ?></h3>

<div class="tva-modal-b-inner">

	<div class="tva-flex mb-30">
		<div class="tvd-input-field tva-flex-one mr-20">
			<input id="tva-lesson-title" data-bind="post_title" value="<#= model.get('post_title') #>" type="text" placeholder="<?php echo esc_html__( 'Lesson Title', 'thrive-apprentice' ); ?>">
			<label>&nbsp;</label>
		</div>

		<div class="ta-flex-250">
			<select name="tva-lesson-type" id="tva-lesson-type" data-bind="lesson_type"></select>
		</div>
	</div>

	<label class="course-label tvd-tooltipped" data-position="right" data-tooltip="This will be displayed on the course overview page."><?php echo esc_html__( 'Description', 'thrive-apprentice' ); ?></label>

	<div class="textarea-box">
		<textarea name="tva-lesson-description" id="tva-lesson-description" data-bind="post_excerpt"><#= model.get('post_excerpt') #></textarea>
	</div>

	<div class="tva-flex tva-align-center tva-space-between mt-30 mb-30">
		<span class="tva-details-title">
			<?php echo esc_html__( 'Allow users comment on this lesson', 'thrive-apprentice' ); ?>
		</span>

		<div class="ta-flex-250">
			<select data-bind="comment_status" id="tva-comment-status">
				<option value="closed"><?php echo esc_html__( 'No', 'thrive-apprentice' ); ?></option>
				<option value="open"><?php echo esc_html__( 'Yes', 'thrive-apprentice' ); ?></option>
			</select>
		</div>
	</div>

	<div id="tva-lesson-options">
		<div id="tva-lesson-text-options" style="display: none;">
			<label class="course-label"><?php echo esc_html__( 'Would you like to add a custom lesson cover image?', 'thrive-apprentice' ); ?></label>
			<div id="tva-lesson-image" class="tva-details-thumb tva-details-cover"></div>
		</div>
		<div class="tva-modal-opts tva-flex tva-flex-one mb-20" id="tva-lesson-audio-options" style="display: none;"></div>
		<div class="tva-modal-opts tva-flex tva-flex-one mb-20" id="tva-lesson-video-options" style="display: none;"></div>
	</div>
</div>
