<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>
<h3 class="tvd-modal-title"><?php echo esc_html__( 'Add Module', 'thrive-apprentice' ); ?></h3>

<div class="tva-modal-b-inner">
	<div class="tvd-input-field">
		<input id="tva-module-title" data-bind="post_title" value="<#= model.get('post_title') #>" type="text" placeholder="<?php echo esc_html__( 'Module Title', 'thrive-apprentice' ); ?>">
		<label>&nbsp;</label>
	</div>

	<label class="course-label mt-30 tvd-tooltipped" data-position="right" data-tooltip="This will be displayed on the course overview page."><?php echo esc_html__( 'Description', 'thrive-apprentice' ); ?>
	</label>

	<div class="textarea-box">
		<textarea id="tva-module-description" data-bind="post_excerpt"><#= model.get('post_excerpt') #></textarea>
	</div>

	<div class="tva-flex tva-align-center tva-space-between mt-30 mb-30">
		<span class="tva-details-title">
			<?php echo esc_html__( 'Allow users comment on this module', 'thrive-apprentice' ); ?>
		</span>

		<div class="ta-flex-250">
			<select data-bind="comment_status" id="tva-comment-status">
				<option value="closed"><?php echo esc_html__( 'No', 'thrive-apprentice' ); ?></option>
				<option value="open"><?php echo esc_html__( 'Yes', 'thrive-apprentice' ); ?></option>
			</select>
		</div>
	</div>

	<label class="course-label"><?php echo esc_html__( 'Would you like to add a custom module cover image?', 'thrive-apprentice' ); ?></label>
	<div id="tva-module-image" class="tva-details-thumb tva-details-cover"></div>
</div>
