<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-apprentice
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden!
}
$config = array(
	'disable_submenu_item' => 'index',
);


?>
<div class="tva-sidebar-wrapper">
	<?php include dirname( __FILE__ ) . '/partial-header.php'; ?>

	<div class="scrollbar-inner w-166">
		<div class="pr-5 pl-5 mb-10">
			<div class="tva-settings-card">
				<div class="tva-settings-card-title">
					<h3 class="tva-course-list-title"><?php echo __( 'Course lessons', TVA_Const::T ) ?></h3>
				</div>

				<div class="tva-settings-card-content">
					<div class="tva-settings-card-inner">
					<div class="tva-clear">
						<label for="tva-lessons-text" class="settings-label"><?php echo __( 'Plural', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('lessons_plural_text') ? 'tvd-tooltipped' : ''#>"
						<#= this.model.get('preview_option') && !available_settings.get('lessons_plural_text') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-lessons-text" name="course_lessons_plural" value="<#= template.course_lessons_plural #>"/>
					</div>
					</div>
				</div>
			</div>

			<div class="tva-settings-card">
				<div class="tva-settings-card-title">
					<h3 class="tva-course-list-title"><?php echo __( 'Course type labels', TVA_Const::T ) ?></h3>
				</div>
				<div class="tva-settings-card-content">
					<div class="tva-settings-card-inner">
						<label for="tva-course-type-guide" class="settings-label"><?php echo __( 'Guide', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('guide') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('guide') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-course-type-guide" name="course_type_guide" value="<#= template.course_type_guide #>"/>

						<label for="tva-course-type-text" class="settings-label"><?php echo __( 'Text', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('text') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('text') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-course-type-text" name="course_type_text" value="<#= template.course_type_text #>"/>

						<label for="tva-course-type-audio" class="settings-label"><?php echo __( 'Audio', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('audio') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('audio') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-course-type-audio" name="course_type_audio" value="<#= template.course_type_audio #>"/>

						<label for="tva-course-type-video" class="settings-label"><?php echo __( 'Video', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('video') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('video') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-course-type-video" name="course_type_video" value="<#= template.course_type_video #>"/>

						<label for="tva-course-type-audio-text-mix" class="settings-label"><?php echo __( 'Audio/text', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('audio_text_mix') ? 'tvd-tooltipped' : ''#>"
						<#= this.model.get('preview_option') && !available_settings.get('audio_text_mix') ? 'disabled ' + available_settings.get('tooltip') :
						''#> id="tva-course-type-audio-text-mix" name="course_type_audio_text_mix" value="<#= template.course_type_audio_text_mix #>"/>

						<label for="tva-course-type-video-text-mix" class="settings-label"><?php echo __( 'Video/text', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('video_text_mix') ? 'tvd-tooltipped' : ''#>"
						<#= this.model.get('preview_option') && !available_settings.get('video_text_mix') ? 'disabled ' + available_settings.get('tooltip') :
						''#> id="tva-course-type-video-text-mix" name="course_type_video_text_mix" value="<#= template.course_type_video_text_mix #>"/>

						<label for="tva-course-type-video-audio-mix" class="settings-label"><?php echo __( 'Video/audio', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('video_audio_mix') ? 'tvd-tooltipped' : ''#>"
						<#= this.model.get('preview_option') && !available_settings.get('video_audio_mix') ? 'disabled ' + available_settings.get('tooltip') :
						''#> id="tva-course-type-video-audio-mix" name="course_type_video_audio_mix" value="<#= template.course_type_video_audio_mix #>"/>

						<label for="tva-course-type-big-mix" class="settings-label"><?php echo __( 'Video/audio/text', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('big_mix') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('big_mix') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-course-type-big-mix" name="course_type_big_mix" value="<#= template.course_type_big_mix #>"/>
					</div>
				</div>
			</div>

			<div class="tva-settings-card">
				<div class="tva-settings-card-title">
					<h3><?php echo __( 'Progress bar', TVA_Const::T ) ?></h3>
				</div>

				<div class="tva-settings-card-content">
					<div class="tva-settings-card-inner">
						<label for="tva-progress-bar-text" class="settings-label"><?php echo __( 'Progress label', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('progress') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('progress') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-progress-bar-text" name="progress_bar" value="<#= template.progress_bar #>"/>

						<label for="tva-progress-bar-text" class="settings-label"><?php echo __( 'Progress not started', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText" class="input settings-input" id="tva-progress-bar-text-not-started" name="progress_bar_not_started"
							   value="<#= template.progress_bar_not_started #>"/>

						<label for="tva-progress-bar-finished-text" class="settings-label"><?php echo __( 'Progress finished', TVA_Const::T ) ?></label>
						<input type="text" data-fn="changeText"
							   class="input settings-input <#= this.model.get('preview_option') && !available_settings.get('finished') ? 'tvd-tooltipped' : ''#>" <#=
						this.model.get('preview_option') && !available_settings.get('finished') ? 'disabled ' + available_settings.get('tooltip') : ''#>
						id="tva-progress-bar-finished-text" name="progress_bar_finished" value="<#= template.progress_bar_finished #>"/>
					</div>
				</div>
			</div>

			<div class="tva-settings-card">
				<div class="tva-settings-card-title">
					<h3><?php echo __( 'Search label', TVA_Const::T ) ?></h3>
				</div>

				<div class="tva-settings-card-content">
					<div class="tva-settings-card-inner">
						<label for="tva-progress-bar-text" class="settings-label"><?php echo __( 'Search', TVA_Const::T ); ?></label>
						<input type="text" data-fn="changeAttribute" class="input settings-input" data-attr-name="placeholder" id="tva-search-text" name="search_text" value="<#= template.search_text #>"/>
					</div>
				</div>
			</div>
		</div>
	</div>

	<?php include dirname( __FILE__ ) . '/save-btn.php'; ?>
</div>
