<?php

/**
 * @var $done   string
 * @var $module WP_Post
 */

$done    = tva_is_module_completed( $module ) ? 'done' : '';
$allowed = tva_access_manager()->has_access_to_post( $module );
?>
<div class="tva-cm-module <?php echo $done; ?>">
	<?php if ( false === $allowed ) : ?>
		<?php $label_id = get_term_meta( $module->course_id, 'tva_label', true ); ?>
		<?php $label = tva_get_labels( array( 'ID' => $label_id ) ); ?>
		<span class="tva-cm-members-only">
			<span>
				<?php echo ! empty( $label['title'] ) ? $label['title'] : __( 'Members Only' ); ?>
			</span>
		</span>
	<?php endif; ?>
	<div class="tva-module-header">
		<span class="tva-collapsible-pointer">
			<?php if ( count( $module->chapters ) === 0 ) : ?>
				<?php echo count( $module->lessons ) . ' ' . _n( 'Lesson', 'Lessons', count( $module->lessons ), 'thrive-apprentice' ); ?>
			<?php else: ?>
				<?php echo count( $module->chapters ) . ' ' . _n( 'Chapter', 'Chapters', count( $module->chapters ), 'thrive-apprentice' ); ?>
			<?php endif; ?>

			<?php tva_get_svg_icon( 'collapsible-minus' ); ?>
			<?php tva_get_svg_icon( 'collapsible-plus' ); ?>
		</span>
		<h2>
			<a class="tva_module_headline" href="<?php echo get_permalink( $module->ID ); ?>">
				<?php echo $module->post_title; ?>
			</a>
			<?php if ( $done ) : ?>
				<span class="tva-cm-module-completed">
					<?php echo tva_get_svg_icon( 'green-check', '', true ); ?>
					<?php echo __( 'Completed', 'thrive-apprentice' ); ?>
				</span>
			<?php endif; ?>
		</h2>
		<?php if ( $module->post_excerpt ) : ?>
			<div class="tva-cm-description">
				<div class="tva_paragraph"><?php echo $module->post_excerpt; ?></div>
			</div>
		<?php endif; ?>
	</div>
	<?php if ( ! empty( $module->chapters ) ) : ?>
		<div class="tve-chapters-wrapper">
			<?php foreach ( $module->chapters as $chapter ) : ?>
				<?php echo tva_generate_chapter_html( $chapter, $allowed ); ?>
			<?php endforeach;; ?>
		</div>
	<?php elseif ( $module->lessons ): ?>
		<div class="tve-lessons-wrapper">
			<?php foreach ( $module->lessons as $lesson ): ?>
				<?php echo tva_generate_lesson_html( $lesson, $allowed ); ?>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>
</div>
