<div class="control-grid<#=this.get_extra_class()#>">
	<div class="label"><#= this.get_config( 'name' ) || this.get_config('label') || this.el.dataset.name #>
		<# if ( this.model.config.instructions ) { #>
		<span class="click" data-type="<#=this.model.config.instructions.type#>" data-url="<#=this.model.config.instructions.url#>" data-link="<#=this.model.config.instructions.link#>" data-fn="openInstructionsLightbox"><#= TVE.icon( this.model.config.instructions.type + "-instructions" ) #></span>
		<# } #>
	</div>

	<div class="input">
		<select class="tve-select change" data-fn="changed">
			<# _.each(this.get_options(), function(option) { #>
			<option class="tve-option <#= option.class #>" value="<#= option.value #>"
			<#= option.default? ' selected':'' #>><#= option.name #></option>
			<# }); #>
		</select>
	</div>
</div>
