<?php
/**
 * Thrive Themes - https://thrivethemes.com
 *
 * @package thrive-university
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<h1 class="tva-main-heading mb-30"><?php echo __( 'Login & Registration Page', TVA_Const::T ) ?></h1>

<div class="tva-login-card">
	<p>
		<?php echo __( 'On what page would you like your login & registration page to be?', 'thrive-apprentice' ) ?>
	</p>

	<p>
		<a href="https://thrivethemes.com/tkb_item/how-to-set-up-the-login-page-in-thrive-apprentice/" target="_blank"><?php _e( ' Learn more about the login & registration page', TVA_Const::T ); ?></a>
	</p>

	<div class="tva-login-states-container mt-50"></div>
</div>
